### ISSUE TITLE
'Float' is a special class name

### ISSUE THREAD

**Issue by ZizzyZizzy** [PocketMine/php-build-scripts#23]
php 7.0.2 compiled fine using compile.sh
installer.sh -u downloads PocketMine-MP.phar, but fails to run:

Fatal error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in phar:///pocketmine/php-build-scripts-php7/PocketMine-MP.phar/src/pocketmine/Server
.php on line 71

**Comment by ZizzyZizzy** [comment]
Even after fixing this, and the same error for String, Double, and Int, it will not run under php7:

Fatal error: Uncaught RuntimeException: Declaration of pocketmine\Thread::start($options = pocketmine\PTHREADS_INHERIT_ALL) should be compatible with Thread::start(int $options = NULL) in phar:///home/pocketmine/php7/php-build-scripts-php7/PocketMine-MP.phar/src/pocketmine/Thread.php:0
Stack trace:
#0 phar:///home/pocketmine/php7/php-build-scripts-php7/PocketMine-MP.phar/src/spl/BaseClassLoader.php(128): ExceptionHandler::handler(2, 'Declaration of ...', 'phar:///home/po...', 0, Array)
#1 phar:///home/pocketmine/php7/php-build-scripts-php7/PocketMine-MP.phar/src/spl/BaseClassLoader.php(128): include()
#2 [internal function]: BaseClassLoader->loadClass('pocketmine\\Thre...')
#3 phar:///home/pocketmine/php7/php-build-scripts-php7/PocketMine-MP.phar/src/pocketmine/command/CommandReader.php(26): spl_autoload_call('pocketmine\\Thre...')
#4 phar:///home/pocketmine/php7/php-build-scripts-php7/PocketMine-MP.phar/src/spl/BaseClassLoader.php(128): include('p in phar:///home/pocketmine/php7/php-build-scripts-php7/Pock
etMine-MP.phar/src/pocketmine/Thread.php on line 0


If you're curious about the Float (and others) fix, this is how I got around them:
cd src/pocketmine/nbt/tag
for type in String Int Float Double; do echo $type; mv $type.php PM$type.php; perl -pi -e 's/class $type/class PM$type/g' PM$type.php; done
cd -
cd src/pocketmine
for type in String Int Float Double; do
echo $type
for file in `find . -name \*.php -exec grep -cH "new $type("  {} \; | grep -v ':0' `; do file=${file%:*}; echo $file;  perl -pi -e "s/new $type\(/new PM$type\(/g" $file; done
for file in `find . -name \*.php -exec egrep -cH "use.*$type;$"  {} \; | grep -v ':0' `; do file=${file%:*}; echo $file;  perl -pi -e "s/\\\\$type;/\\\\PM$type;/g" $file; done
done

You have to unpack the phar first:

mkdir unpacked
php unphar.php

Here is the unphar.php script:
<?php
$phar = new Phar('PocketMine-MP.phar');
$phar->extractTo('./unpacked');
?>

**Comment by ZizzyZizzy** [comment]
Anyone else running into this issue, the correct pocketmine source for PHP 7 can be cloned like so:

git clone --recursive --branch=php7 https://github.com/PocketMine/PocketMine-MP.git PocketMine/PocketMine-MP

If it's missing anything from src/spl or src/raklib, you'll have to grab them from an old, unpacked PocketMine-MP.phar file. I just ran rsync and it works fine. API 2.0.0, however. Plugins no longer work.
